name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Clear npm config and force public registry
        run: |
          rm -f ~/.npmrc || true
          rm -f .npmrc || true
          echo "registry=https://registry.npmjs.org/" > .npmrc
          npm config set registry https://registry.npmjs.org/
          npm config list
          
      - name: Remove package-lock and reinstall with public registry
        run: |
          rm -f package-lock.json
          npm install
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and export
        run: npm run export
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4